# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f2a59ddd2720a86d9cdc273b27e962e456c2d24d906f56070532365b11fcb7527e563df4ce90ae3c87e06b72f84fe0b82a1fd45fa7e48a6b8a8f93ba1c8fef

test:
  secret_key_base: fcb4528df367d68d4b6ab3e3f8f24e04999ffb7d237d109e3ab6b721add10b6466914c62e9c509cc0d28a6d99e6a653e0c888a9c216a095eb794dc22006e6d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
